### ISSUE TITLE
需要写同步脚本把users表中的相关属性更新到各个工作区的space_users表中

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-accounts#42]
且同一账户的多个spaces中space_users记录相关属性应该更新为一致。
参考文档：[Steedos 支持SAAS多租户的运行模式。](https://github.com/steedos/steedos-website/blob/master/docs/accounts/index.md)

- [ ] 对照以下表格把yml文件中users及space_users对象中缺少的字段加上
- [ ] 左侧为users表字段，需要同步到右侧的users表中对应字段中：

emails.verified | email_verified
phone.verified | mobile_verified

- [ ] 左侧为users表字段，需要同步到右侧的space_users表中对应字段中：

users  | space_users
:-- | :--
name | name
username | username
email | email
email_verified | email_verified
mobile | mobile
mobile_verified | mobile_verified
locale | locale
avatar | avatar
last_logon | last_logon
email_notification | email_notification
sms_notification | sms_notification

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-accounts/issues/44
