### ISSUE TITLE
华信客户端访问新的accounts登录界面很慢很慢

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-accounts#64]
- Mac/windows平台都有这个问题
- 登录进入去再访问或刷新就没这个问题，很快很快
- 未登录状态下会跳转到登录界面，这时很慢很慢
- 连本地跑的creator源码，或线上cn的creator一样慢

![image](https://user-images.githubusercontent.com/6219465/76394549-a2815400-63b0-11ea-8431-ffe1e9c8491f.png)

**Comment by chenzhipei** [comment]
注释loading后可以正常访问
