### ISSUE TITLE
iphone真机华炎手机客户端登录后又跳转到登录界面了，没正常进入登录后的界面

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-accounts#66]
- 是跑的saas项目，配置了rootURL为/creator
- 之前正常登录过一个账户，然后成功登出到登录界面，换一个账户登录就不行了
- 操作视频演示：https://messenger.steedos.cn/steedos/pl/bk4n5396sidetrch6naf6qqy9h

**Comment by yinlianghui** [comment]
退出整个APP，再登录又能正常使用了

**Comment by baozhoutao** [comment]
https://github.com/steedos/creator/commit/c59fc3e657b40045d27535ba616775355499ec42
