### ISSUE TITLE
手机上输入邮箱及密码后，点击下一步容易误触点击到注册或忘记密码链接

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-accounts#67]
而且从注册或忘记密码界面返回到登录界面之后，之前输入的内容被清空了要重新再输入一次，是否考虑就算误触后，返回时能保持上次输入的内容！
![image](https://user-images.githubusercontent.com/6219465/76500919-5865a480-647c-11ea-917b-6a4b0a008ade.png)

**Comment by baozhoutao** [comment]
调整按钮距离
